import { db } from "./db";
import { productTable, salesTable } from "./schema";

async function seed() {
  await db.insert(productTable).values([
    { name: "iPhone 15", stock: 50, category: "electronics", price: 79999 },
    { name: "Samsung S24", stock: 45, category: "electronics", price: 74999 },
    { name: "Pixel 8", stock: 40, category: "electronics", price: 69999 },
    { name: "MacBook Air M2", stock: 20, category: "laptops", price: 129999 },
    { name: "Dell XPS 13", stock: 18, category: "laptops", price: 119999 },
    { name: "HP Pavilion", stock: 25, category: "laptops", price: 89999 },
    { name: "AirPods Pro", stock: 100, category: "accessories", price: 24999 },
    {
      name: "Sony WH-1000XM5",
      stock: 60,
      category: "accessories",
      price: 29999,
    },
    { name: "Apple Watch", stock: 70, category: "wearables", price: 39999 },
    {
      name: "Samsung Galaxy Watch",
      stock: 65,
      category: "wearables",
      price: 34999,
    },

    { name: "iPad Pro", stock: 30, category: "tablets", price: 89999 },
    { name: "Galaxy Tab S9", stock: 28, category: "tablets", price: 79999 },
    {
      name: "Logitech MX Master 3",
      stock: 120,
      category: "accessories",
      price: 9999,
    },
    {
      name: "Mechanical Keyboard",
      stock: 90,
      category: "accessories",
      price: 6999,
    },
    { name: "Gaming Mouse", stock: 110, category: "accessories", price: 4999 },
    { name: '27" Monitor', stock: 35, category: "monitors", price: 29999 },
    { name: '32" Monitor', stock: 22, category: "monitors", price: 39999 },
    { name: "External SSD 1TB", stock: 80, category: "storage", price: 11999 },
    { name: "USB-C Hub", stock: 150, category: "accessories", price: 3999 },
    { name: "Webcam 4K", stock: 45, category: "accessories", price: 14999 },
  ]);

  await db.insert(salesTable).values([
    {
      product_id: 1,
      quantity: 1,
      total_amount: 79999,
      customer_name: "Rahul",
      region: "India",
    },
    {
      product_id: 2,
      quantity: 2,
      total_amount: 149998,
      customer_name: "Amit",
      region: "India",
    },
    {
      product_id: 3,
      quantity: 1,
      total_amount: 69999,
      customer_name: "Sneha",
      region: "India",
    },
    {
      product_id: 4,
      quantity: 1,
      total_amount: 129999,
      customer_name: "John",
      region: "USA",
    },
    {
      product_id: 5,
      quantity: 1,
      total_amount: 119999,
      customer_name: "Emily",
      region: "USA",
    },
    {
      product_id: 6,
      quantity: 2,
      total_amount: 179998,
      customer_name: "Ankit",
      region: "India",
    },
    {
      product_id: 7,
      quantity: 3,
      total_amount: 74997,
      customer_name: "Kunal",
      region: "India",
    },
    {
      product_id: 8,
      quantity: 1,
      total_amount: 29999,
      customer_name: "Rohit",
      region: "India",
    },
    {
      product_id: 9,
      quantity: 1,
      total_amount: 39999,
      customer_name: "Sarah",
      region: "UK",
    },
    {
      product_id: 10,
      quantity: 2,
      total_amount: 69998,
      customer_name: "Daniel",
      region: "USA",
    },

    {
      product_id: 11,
      quantity: 1,
      total_amount: 89999,
      customer_name: "Neha",
      region: "India",
    },
    {
      product_id: 12,
      quantity: 2,
      total_amount: 159998,
      customer_name: "Arjun",
      region: "India",
    },
    {
      product_id: 13,
      quantity: 2,
      total_amount: 19998,
      customer_name: "Vikas",
      region: "India",
    },
    {
      product_id: 14,
      quantity: 1,
      total_amount: 6999,
      customer_name: "Chris",
      region: "USA",
    },
    {
      product_id: 15,
      quantity: 3,
      total_amount: 14997,
      customer_name: "Aman",
      region: "India",
    },
    {
      product_id: 16,
      quantity: 1,
      total_amount: 29999,
      customer_name: "Laura",
      region: "UK",
    },
    {
      product_id: 17,
      quantity: 1,
      total_amount: 39999,
      customer_name: "Mike",
      region: "USA",
    },
    {
      product_id: 18,
      quantity: 2,
      total_amount: 23998,
      customer_name: "Nikhil",
      region: "India",
    },
    {
      product_id: 19,
      quantity: 4,
      total_amount: 15996,
      customer_name: "Suresh",
      region: "India",
    },
    {
      product_id: 20,
      quantity: 1,
      total_amount: 14999,
      customer_name: "Olivia",
      region: "USA",
    },

    {
      product_id: 1,
      quantity: 2,
      total_amount: 159998,
      customer_name: "Ravi",
      region: "India",
    },
    {
      product_id: 2,
      quantity: 1,
      total_amount: 74999,
      customer_name: "Pooja",
      region: "India",
    },
    {
      product_id: 3,
      quantity: 2,
      total_amount: 139998,
      customer_name: "Manish",
      region: "India",
    },
    {
      product_id: 4,
      quantity: 1,
      total_amount: 129999,
      customer_name: "Steve",
      region: "USA",
    },
    {
      product_id: 5,
      quantity: 2,
      total_amount: 239998,
      customer_name: "Anna",
      region: "UK",
    },
    {
      product_id: 6,
      quantity: 1,
      total_amount: 89999,
      customer_name: "Vivek",
      region: "India",
    },
    {
      product_id: 7,
      quantity: 2,
      total_amount: 49998,
      customer_name: "Harsh",
      region: "India",
    },
    {
      product_id: 8,
      quantity: 2,
      total_amount: 59998,
      customer_name: "Nitin",
      region: "India",
    },
    {
      product_id: 9,
      quantity: 1,
      total_amount: 39999,
      customer_name: "Emma",
      region: "USA",
    },
    {
      product_id: 10,
      quantity: 1,
      total_amount: 34999,
      customer_name: "Lucas",
      region: "UK",
    },

    {
      product_id: 11,
      quantity: 1,
      total_amount: 89999,
      customer_name: "Karan",
      region: "India",
    },
    {
      product_id: 12,
      quantity: 1,
      total_amount: 79999,
      customer_name: "Meera",
      region: "India",
    },
    {
      product_id: 13,
      quantity: 3,
      total_amount: 29997,
      customer_name: "Abhishek",
      region: "India",
    },
    {
      product_id: 14,
      quantity: 2,
      total_amount: 13998,
      customer_name: "Ryan",
      region: "USA",
    },
    {
      product_id: 15,
      quantity: 1,
      total_amount: 4999,
      customer_name: "Deepak",
      region: "India",
    },
    {
      product_id: 16,
      quantity: 1,
      total_amount: 29999,
      customer_name: "Sophia",
      region: "UK",
    },
    {
      product_id: 17,
      quantity: 2,
      total_amount: 79998,
      customer_name: "Noah",
      region: "USA",
    },
    {
      product_id: 18,
      quantity: 1,
      total_amount: 11999,
      customer_name: "Ajay",
      region: "India",
    },
    {
      product_id: 19,
      quantity: 2,
      total_amount: 7998,
      customer_name: "Sunil",
      region: "India",
    },
    {
      product_id: 20,
      quantity: 1,
      total_amount: 14999,
      customer_name: "Isabella",
      region: "UK",
    },
  ]);
}

seed();
